### ISSUE TITLE
Firefoxで画像のURLにテンプレート変数が使われたケースで、パースに失敗する

### ISSUE THREAD

**Issue by fuji3zpg** [osscafe/yinyang#9]

**Comment by cognitom** [comment]
Firefoxの仕様で、URLっぽい文字列が指定されると、自動的にURLエンコードされてしまうようです。

``` html
<img src="#{book.image|default:../style/images/book-no-image.png}" />
```

上記のようなケースで、defaultフィルタの引数として指定された文字列が、URLだと判断されるみたい...。
代替画像のURLが暫定対応として、"|"(パイプ)の文字のURLデコードをかけてからパースするようにした、ver 0.2.8をリリースしました。

**Comment by cognitom** [comment]
お陰さまで、OSSCafeサイトのトップページの画像も正しく表示されるようになりました :-)
http://www.osscafe.net/ja/
